# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'CCV3Demo' do
pod 'KalturaPlayerSDK
pod 'google-cast-sdk’, '~> 3.2.0'
#pod 'GoogleAds-IMA-iOS-SDK’ , '~> 3.2.1’
end
