# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'LocalAssetsDemo' do
    pod 'KalturaPlayerSDK', :git => 'https://github.com/kaltura/player-sdk-native-ios.git', :branch => 'develop'
    pod 'DownPicker'
    pod 'M3U8Parser', :git => 'https://github.com/srivkas/M3U8Parser.git', :branch => 'master'
    pod 'FMDB', :git => 'https://github.com/srivkas/fmdb', :branch => 'rp_xcode8'
    
    #Please use DownloadToGo as local Framework,
    #First, you should take access for project DovnloadToGo(https://github.com/kaltura/download-to-go-ios/tree/Xcode8_v3)
    #Second, please clone it and save path
    pod 'DownloadToGo', :path => '...Your Local Path'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
