# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LocalAssetsDemo' do
    pod 'KalturaPlayerSDK/Core',      :git => 'https://github.com/kaltura/player-sdk-native-ios', tag: 'v2.6.8'
    pod 'KalturaPlayerSDK/Widevine',  :git => 'https://github.com/kaltura/player-sdk-native-ios', tag: 'v2.6.8'
    pod 'DownPicker'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
