# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'KalturaSample' do
pod 'KalturaPlayerSDK', :git => 'https://github.com/kaltura/player-sdk-native-ios.git', :branch => 'develop'
pod 'GoogleAds-IMA-iOS-SDK’ , '~> 3.1.0’
pod 'google-cast-sdk' , '~> 2.10.4'
end

target 'KalturaSampleTests' do

end

target 'KalturaSampleUITests' do

end

