# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'CCDemo' do
pod 'KalturaPlayerSDK'
pod 'google-cast-sdk' , '~> 2.10.4’
pod 'GoogleAds-IMA-iOS-SDK’ , '~> 3.2.1’
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
