# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'KalturaCCSample' do
pod 'KalturaPlayerSDK' , :path => '~/Documents/KALTURA/playerSDKNativeIos'
pod 'GoogleAds-IMA-iOS-SDK’ , '~> 3.1.0’
pod 'google-cast-sdk' , '~> 2.10.4'
end

